### PR TITLE
viewer sample: wrap datachannel callback with `ENABLE_DATA_CHANNEL`

### PR DESCRIPTION
**Pull request by codingspirit**
Signed-off-by: zhiqinli@amazon.com <zhiqinli@amazon.com>

*Issue #, if available:*
In viewer sample, some data channel related functions were not wrapped by `ENABLE_DATA_CHANNEL`.

*Description of changes:*
This change will wrap datachannel callback in viewer samples with `ENABLE_DATA_CHANNEL`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by codingspirit** [comment]
BTW, in current code base, sdk has dependencies on `libusrsctp` even if `ENABLE_DATA_CHANNEL` was switched to `OFF`. This maybe can be tracked as an issue.

**Comment by disa6302** [comment]
@codingspirit ,

Thank you for your PR! Can you open this against `develop` instead of `master`? 
@niyatim23 , can you confirm the changes are good?

**Review by niyatim23 — DISMISSED** [review]
Looks good to me! Thank you for the PR, needs to be moved to the _develop_ branch

**Comment by codingspirit** [comment]
@niyatim23 Target branch changed to `develop`

**Comment by niyatim23** [comment]
Hi @codingspirit, thanks for moving the PR to develop, however, some unwanted commits were pulled in when you made the move. Can you please rebase off develop and create a new PR so that this is fixed?
Thank you for this. Appreciate it.

**Review by disa6302 — APPROVED** [review]

**Review by niyatim23 — APPROVED** [review]

**Pull request merged**
