### PR TITLE
Fixing interlocking issues and bugs with transaction store for srflx …

### PR DESCRIPTION
**Pull request by MushMal**
…candidates

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by hassanctech — COMMENTED** [review]
Can we please get a test for this fix?  It might be easier to understand the change when I can see a test that would have previously have failed.

**Comment by MushMal** [comment]
> Can we please get a test for this fix? It might be easier to understand the change when I can see a test that would have previously have failed.

It's not trivial and will require full integ test. Some of the changes are for the negative path. I am not sure what the root cause is for the case where srflx candidate was not being selected.

**Review by disa6302 — APPROVED** [review]
LGTM!

**Review by hassanctech — APPROVED** [review]

**Comment by MushMal** [comment]
Just want to confirm that after multiple experiments, srflx candidate does get selected and used in case when only TURN and SRFLX are available.

**Pull request merged**
