### PR TITLE
Add an optional flag to not include samples

### PR DESCRIPTION
**Pull request by lherman-cs**
When users want to use our SDK as a library, it's not necessary to also compile samples. So, this PR will give them an ability to not compile the samples.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lherman-cs** [comment]
* There's no particular ask, but I found this to be the common pattern for having this optional. And, I think it's a good practice to separate them, samples might have dependencies that the libraries don't depend.
* I'm making BUILD_SAMPLE to be on by default because customers might've been used to this behavior.

**Comment by MushMal** [comment]
> * There's no particular ask, but I found this to be the common pattern for having this optional. And, I think it's a good practice to separate them, samples might have dependencies that the libraries don't depend.
> * I'm making BUILD_SAMPLE to be on by default because customers might've been used to this behavior.

Sounds great then

**Comment by ycyang1229** [comment]
> When users want to use our SDK as a library, it's not necessary to also compile samples. So, this PR will give them an ability to not compile the samples.
> 
> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

I like this idea, but do you mind adding three more options for kvsWebrtcClientMaster, kvsWebrtcClientViewer, and kvsWebrtcClientMasterGstSample separately below this option BUILD_SAMPLE? Sometimes, customers only need one part of kvs samples.

**Comment by MushMal** [comment]
> > When users want to use our SDK as a library, it's not necessary to also compile samples. So, this PR will give them an ability to not compile the samples.
> > By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> 
> I like this idea, but do you mind adding three more options for kvsWebrtcClientMaster, kvsWebrtcClientViewer, and kvsWebrtcClientMasterGstSample separately below this option BUILD_SAMPLE? Sometimes, customers only need one part of kvs samples.

I would recommend avoiding the complexity in the build scripts as those are very hard to debug and get right for various platforms. Could you perhaps give some examples when compiling the samples is difficult?

**Comment by lherman-cs** [comment]
> > When users want to use our SDK as a library, it's not necessary to also compile samples. So, this PR will give them an ability to not compile the samples.
> > By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> 
> I like this idea, but do you mind adding three more options for kvsWebrtcClientMaster, kvsWebrtcClientViewer, and kvsWebrtcClientMasterGstSample separately below this option BUILD_SAMPLE? Sometimes, customers only need one part of kvs samples.

@ycyang1229 I think for this use case, the customer should not compile with just `make` but instead,  `make <specific example>`.

**Pull request merged**
