### PR TITLE
fixed the static build issue.

### PR DESCRIPTION
**Pull request by ycyang1229**
*Issue #, if available:*
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/665
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/664

*Description of changes:*
Changed the setting of static build in the cmakelists.txt

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lherman-cs** [comment]
@ycyang1229 it looks like the change failed only on mac

**Comment by ycyang1229** [comment]
> @ycyang1229 it looks like the change failed only on mac

I did not try it on mac, but it should be fine on ubuntu. I can build it on mac successfully without this commit, although it is not a real static build at that time.  I also think it can not work on window, since the find_lib for usrsctp may need to be changed as *.lib or something else.

**Comment by ycyang1229** [comment]
> > @ycyang1229 it looks like the change failed only on mac
> 
> I did not try it on mac, but it should be fine on ubuntu. I can build it on mac successfully without this commit, although it is not a real static build at that time. I also think it can not work on window, since the find_lib for usrsctp may need to be changed as *.lib or something else.

failed on mac probably because of the same reason, since the file extension of mac is *.dylib.

**Comment by shiv50084** [comment]
Can you please review my changes for static build that done in following files:-
>>>>>>>>>>  CMakeLists.txt
 # static settings
 if(BUILD_STATIC_LIBS OR WIN32)
   set(LINKAGE STATIC)
@@ -67,13 +79,13 @@ if(BUILD_DEPENDENCIES)
   endif()

   if (USE_OPENSSL)
-    set(BUILD_ARGS -DBUILD_STATIC=${BUILD_STATIC}
+    set(BUILD_ARGS -DBUILD_STATIC_LIBS=${BUILD_STATIC_LIBS}
                    -DBUILD_OPENSSL_PLATFORM=${BUILD_OPENSSL_PLATFORM}
                    -DOPENSSL_EXTRA=${OPENSSL_EXTRA})
     build_dependency(openssl ${BUILD_ARGS})
     set(OPENSSL_ROOT_DIR ${OPEN_SRC_INSTALL_PREFIX})
   elseif(USE_MBEDTLS)
-    set(BUILD_ARGS -DBUILD_STATIC=${BUILD_STATIC})
+    set(BUILD_ARGS -DBUILD_STATIC_LIBS=${BUILD_STATIC})
     build_dependency(mbedtls ${BUILD_ARGS})
   endif()



>>>>>>>>>>> 
diff --git a/CMake/Dependencies/libwebsockets-CMakeLists.txt b/CMake/Dependencies/libwebsockets-CMakeLists.txt
index 24e832d..1973103 100644
--- a/CMake/Dependencies/libwebsockets-CMakeLists.txt
+++ b/CMake/Dependencies/libwebsockets-CMakeLists.txt
@@ -4,7 +4,7 @@ project(libwebsocket-download NONE)

 include(ExternalProject)

-if (BUILD_STATIC)
+if (BUILD_STATIC_LIBS)
   set(LWS_WITH_STATIC 1)
   set(LWS_WITH_SHARED 0)
 else()



>>>>>>>>>>>>>

**Comment by MushMal** [comment]
What's the latest on this PR?

**Comment by ycyang1229** [comment]
@MushMal , shiv50084's change and my pr look like the same idea, but I hope the argument of static-build can be consistent across webrtc, producer, and pic. I did not try it on mac and windows, since I never built it with clang successfully on my mac(I use gcc-9 toolchain on my mac instead) and I do not have a window pc. Maybe you can add some change for mac clang and windows.
@shiv50084, you need to change your BUILD_STATIC in libmedtls-CMakLists.txt if you want to use DBUILD_STATIC_LIBS for mbedtls.

**Comment by MushMal** [comment]
These are the type of changes that are really hard to get right, unfortunately. This is due to the test/build matrix. Let's try to not lose this

**Pull request closed without merging**
