### PR TITLE
add support for CN region

### PR DESCRIPTION
**Pull request by codingspirit**
Signed-off-by: Alex Li <zhiqinli@amazon.com>

*Issue #, if available:*
KVS is now available in [China region](https://www.amazonaws.cn/en/new/2023/amazon-kinesis-video-streams-is--available-in-the-amazon-web-services-china-beijing-region-operated-by-sinnet/?nc1=h_ls)

In China region, all API endpoint will have postfix ".amazonaws.com.cn" instead of ".amazonaws.com". Use current SDK will cause DNS resolving error when call APIs in KVS control plane. Similar issue can be observed in Producer SDK as well.

See https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/pull/344

*Description of changes:*
This commit will generate correct `controlPlaneUrl` and STUN server url according to configured region.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by hassanctech — APPROVED** [review]
lgtm

**Comment by codingspirit** [comment]
working on it...

**Comment by codingspirit** [comment]
@hassanctech Failing tests should be fixed now

**Review by hassanctech — APPROVED** [review]
lgtm

**Pull request merged**
