### PR TITLE
Fix missing mutex_unlock on error

### PR DESCRIPTION
**Pull request by ek9852**
Issue: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/128

The CHK_WARN, CHK_ERR, CHK_STATUS will do a goto
and might skip the MUTEX_UNLOCK, there
are some code path does not happened that properly.

Fixing it.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ek9852** [comment]
@chehefen, @Sean-Der

**Comment by Sean-Der** [comment]
Fantastic, thank you so much @ek9852 

I wish we had a better way to this, have a scoped locks would be really nice (but not portable unfortunately). Maybe we can come up with some tooling that requires `unlock` can only be after `CleanUp:` ?

**Comment by ek9852** [comment]
This might increase the locked time for the code if only unlock in cleanup and depends on how long those are. Unfortunately this is a c library, otherwise we can use c++ object lock to lock a scope of code and release it after it is out of scope.

**Comment by Sean-Der** [comment]
> This might increase the locked time for the code if only unlock in cleanup and depends on how long those are. Unfortunately this is a c library, otherwise we can use c++ object lock to lock a scope of code and release it after it is out of scope.

That's a good point. Maybe if you are doing a lock you need to push the code that takes the lock into a smaller function.

I just really hate walking away from an issue with fixing the 'root cause'

**Comment by ek9852** [comment]
me too, but there are quite a number of code inside the sdk using the locked variable to do that.
I don't have a brilliant idea on that just using pure portable C. Possible that the  reason why there is another implement using Go for webrtc. :)

**Comment by Sean-Der** [comment]
@ek9852 merged with d633a918a2dd125bb1e0f4d0196056a0e15dac0d

Whoever did Go in WebRTC sounds like they really to make life hard on themselves, I would avoid them :p 

I really appreciate you bringing this issue up, and anything you bring up on this repo I would love to improve! I am all over the place, but I really love getting others involved/getting feedback :)

**Pull request closed without merging**
