### PR TITLE
fix WSAPoll failed when set POLLPRI flag

### PR DESCRIPTION
**Pull request by Dw9**
when I run kvs on windows11, Poll failed.

image
ref:
[ If the POLLPRI flag is set on a socket for the Microsoft Winsock provider, the WSAPoll function will fail.](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsapoll#:~:text=If%20the%20POLLPRI%20flag%20is%20set%20on%20a%20socket%20for%20the%20Microsoft%20Winsock%20provider%2C%20the%20WSAPoll%20function%20will%20fail.)

### CODE REVIEW

**Comment by niyatim23** [comment]
Hi @Dw9, thank you for your contribution. Can you please rebase this to the latest changes in develop?

**Comment by Dw9** [comment]
@niyatim23 Thank you for your reply。 :)
I selected the branch develop , It seems wrong...

**Comment by sirknightj** [comment]
Hey @Dw9 , it seems something went wrong with the rebase, and we also have some merge conflicts. I'll create a new PR on your behalf with your changes.

**Comment by niyatim23** [comment]
Hi @Dw9, your changes have been merged. Thanks for your contribution! We appreciate it. Closing this PR in favor of https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/1636

**Pull request closed without merging**
