### PR TITLE
Samples build fix

### PR DESCRIPTION
**Pull request by mateuszboryn**
*Issue #, if available:*

*Description of changes:*

- Moved samples to separate CMake project, with minimal changes to the code base.
- Added ability to build samples independently of main CMake project, after main project is installed in some directory (preferably the same location as OPEN_SRC_INSTALL_PREFIX).
- When setting OPEN_SRC_INSTALL_PREFIX to something different than default (to reduce build time with multiple libraries) it used to fail. Introducing cached variable OPEN_SRC_INSTALL_PREFIX and fixing patching scripts resolved that problem.
- from now on it should be much easier to build custom samples outside of this repository, with minimal CMake boilerplate.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by disa6302** [comment]
@mateuszboryn , 

Thanks for the PR and apologies for the delayed response. Will take a look at this PR and get back ASAP.

**Comment by disa6302** [comment]
@mateuszboryn ,

Thank you for the `OPEN_INSTALL_PREFIX` fix! Looks good to me. 

About the samples, I am wondering why we would need a separate CMake file? We can have an option to build samples such as `-CMAKE_BUILD_SAMPLES=OFF/ON` instead, correct?

**Comment by mateuszboryn** [comment]
Thank you @disa6302 for reviewing,

_About the samples, I am wondering why we would need a separate CMake file? We can have an option to build samples such as `-CMAKE_BUILD_SAMPLES=OFF/ON` instead, correct?_

Indeed, building samples can be controlled with that flag. However separate `samples/CMakeLists.txt` file is at the same time main file for a standalone project, outside of kvsWebrtc source tree.
That makes `samples` directory a complete example how to set up custom project having the kvsWebrtc library already built and available in `OPEN_SRC_INSTALL_PREFIX` (after performing `make install` in kvsWebrtc).

This way one can build his project, by copying&modifying contents of `samples` directory.

**Comment by disa6302** [comment]
@mateuszboryn , sounds good. It LGTM. I would also like @hassanctech to take a look. One more thing. Can you push a new commit in this pR so that travis-ci can start running? For some weird reason, it seems stuck. We will have to kick off a new build.

**Comment by mateuszboryn** [comment]
Done. Please check now.

**Comment by mateuszboryn** [comment]
Hi @hassanctech , did you happen to have a chance to review this PR? I would be grateful if you could review it and provide some feedback.

**Review by hassanctech — COMMENTED** [review]
LGTM

**Review by hassanctech — APPROVED** [review]

**Comment by mateuszboryn** [comment]
Thank you.

**Comment by hassanctech** [comment]
> Thank you.

Sorry for the delay and thank you for your contribution!!

**Pull request merged**
