### PR TITLE
fix bug: for a 32-bit system will try to cast to 64-bit address we will overflow

### PR DESCRIPTION
**Pull request by hassanctech**
fix bug: for a 32-bit system will try to cast to 64-bit address we will overflow

*Issue #, if available:*
[827](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/827)
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by MushMal — APPROVED** [review]
Great work! Thanks for getting this out in such a short notice. 

To note: this issue could cause both a crash as well as correctness issue on a 32 bit LE machine

**Comment by hassanctech** [comment]
Forgot clang-format the first time.

**Comment by henryChmn** [comment]
I check with webrtc SDK last commit(35fc3ea5 ("Fix static build contains dynamic links (#837)", 2020-10-01)), still have some 64-bit transfer are calling, Does these calling without problems?

image

**Comment by hassanctech** [comment]
You're right @henryChmn I missed those somehow, thank you for bringing them to my attention. Here's another pull request to fix that:  https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/845

**Pull request merged**
